[posts]
	[posts.post1]
	user_id = 1020
	body = 'asd1'
	title = 'title1'

	[posts.post2]
	user_id = 5555
	body = 'asd2'
	title = 'title2'

	[posts.post3]
	user_id = 28
	body = ''
	title = 'title3'

	[posts.post4]
	user_id = 28
	body = 'asd1'
	title = ''

	