title = "users TOML"

[[users]]
name = "test1"
email = "user_test11aaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test2"
email = "user_test22aaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test3"
email = "user_test33aaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test4"
email = "user_test44aaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test5"
email = "user_test55aaa@yahoo.com"
gender = "male"
status = "active"