title = "users TOML"

[[users]]
name = "test1"
email = "User_test111avaaaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test2"
email = "User_test222avaaaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test3"
email = "User_test333aavaaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test4"
email = "User_test444aavaaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test5"
email = "User_test555aaavaa@yahoo.com"
gender = "male"
status = "active"