title = "users TOML"

[[users]]
name = "test1"
email = "User_test111aaaaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test2"
email = "User_test222aaaaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test3"
email = "User_test333aaaaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test4"
email = "User_test444aaaaa@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test5"
email = "User_test555aaaaa@yahoo.com"
gender = "male"
status = "active"