[users]
	[users.user1]
	name = "test1"
	email = "User_test1AAAd11@yahoo.com"
	gender = "male"
	status = "active"

	[users.user2]
	name = "test2"
	email = "User_test2BBBad12@yahoo.com"
	gender = "male"
	status = "active"

	[users.user3]
	name = "test3"
	email = "User_test3CCCa13@yahoo.com"
	gender = "male"
	status = "active"