[[users]]
name = "test1"
email = "User_testsAAVaasd1@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test2"
email = "User_testVAS2s3ed1@yahoo.com"
gender = "male"
status = "active"

[[users]]
name = "test3"
email = "User_test1s1GFed1@yahoo.com"
gender = "male"
status = "active"