[users]
	[users.user1]
	name = "test1"
	email = "User_test1ACVA2Ss2211111@yahoo.com"
	gender = "male"
	status = "active"

	[users.user2]
	name = "test2"
	email = "User_test2JSAL322s3122222@yahoo.com"
	gender = "male"
	status = "active"

	[users.user3]
	name = "test3"
	email = "User_test3CIOWYA2s98133333A@yahoo.com"
	gender = "male"
	status = "active"